# auto-runs on ubuntu trusty
sudo: required

services:
  - docker

language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install .
  - pip install pytest-docker docker-compose pandas

script: pytest
