# auto-runs on ubuntu trusty
sudo: required

services:
  - docker

language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy3'

install:
  - pip install .
  - pip install pytest-docker pytest-cov docker-compose coveralls

script: pytest

after_success: coveralls
