# auto-runs on ubuntu trusty
sudo: required

services:
  - docker

language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

before_install:
  - sudo apt update -qq
  - sudo apt install ldap-utils libldap-2.4-2 libldap2-dev libsasl2-dev

install:
  - pip install .
  - pip install pytest-docker docker-compose

script: pytest
