#!/usr/bin/env python3

import sys
import argparse

import ldaputils

def main():
    parser = argparse.ArgumentParser(description="Creates an LDAP group.")
    parser.add_argument('group_name', nargs=1, type=str, 
            help='LDAP group name to create.')
    parser.add_argument('gid', nargs='?', type=int, default=None,
            help='GID number of group to create. If not supplied, uses next available GID number.')
    parser.add_argument('-n', '--dry-run', default=False, const=True, action='store_const', 
            help='Do a "dry run" (i.e. just print what actions will be performed without doing anything).')
    argv = parser.parse_args()
    groupname = argv.group_name[0]
    gid = argv.gid

    with ldaputils.LDAP() as con:
        # create ldif for use
        vals = ldaputils.get_placeholders(ldaputils.config())
        if gid is None:
            gid = con.next_gidn()

        vals['GID'] = gid
        vals['GROUPNAME'] = groupname
        ldif = ldaputils.LDIF('etc/ldap-add-group.ldif')
        ldif.unplaceholder(vals)
    
        print('\n# Creating group {} with LDIF:'.format(groupname))
        ldif.write()

        if argv.dry_run:
            print('# no changes performed.')
            sys.exit(0)

        con.ldif_add(ldif)

if __name__ == '__main__':
    main()

