#!/usr/bin/env python3

import sys
import argparse
import ldaputils
import ldap

def main():
    parser = argparse.ArgumentParser(
            description='Add a user to an LDAP group.')
    parser.add_argument('USERNAME', nargs=1, type=str, 
            help='An LDAP username to add to a group.')
    parser.add_argument('GROUPNAME', nargs=1, type=str,
            help='An LDAP groupname to add to a group.')
    parser.add_argument('-n', '--dry-run', default=False, 
            const=True, action='store_const', 
            help='Whether or not to do a dry-run ' 
                 '(print changes without executing).')
    argv = parser.parse_args()
    user = argv.USERNAME[0]
    group = argv.GROUPNAME[0]


    with ldaputils.LDAP() as con:
        ldif = ldaputils.LDIF('etc/ldap-add-to-group.ldif')
        replace = {'USERNAME': user, 'GROUPNAME': group}

        # just double checking
        try:
            replace['USERDN'] = con.get_user(user)[0][0]  
        except IndexError:
            sys.exit('User does not exist.')
        if len(con.get_group(group)) != 1:
            sys.exit('Group does not exist.')

        replace.update(con.get_placeholders())
        ldif.unplaceholder(replace)
        ldif.write()

        if argv.dry_run:
            print('No changes performed.', file=sys.stderr)
            sys.exit(0)
        else:
            pass


if __name__ == '__main__':
    main()

