#!/usr/bin/env python3

import argparse
import ldaputils

def main():
    parser = argparse.ArgumentParser(description='Search LDAP tree for a DN keyword and print resulting LDIF.')
    parser.add_argument('keyword', nargs='?', type=str, default='', 
            help='Keyword to search DNs by (case-sensitive). Dumps entire directory if not supplied.')
    argv = parser.parse_args()
    key = argv.keyword

    try:
        con = ldaputils.bind()
        base_dn = ldaputils.base_dn(con)
        # retrieves everything... might not work against huge LDAP directories due to paging limits
        query = con.search_s(base_dn, 2)
        
        # grab all objects with our search key in the DN
        results = [entry for entry in query if key in entry[0]]
        
        # dump results to ldif
        ldif = ldaputils.LDIF()
        for dn, attrs in results:
            ldif.entries[dn] = attrs

        ldif.write()
        
    finally:
        con.unbind_s()


if __name__ == '__main__':
    main()

